export const errorCodes = {
    //AUTHENTICATION CODES
    AUTH_INVALID_CREDENTIALS: 'AUTH_001',
    AUTH_USER_NOT_FOUND: 'AUTH_002',
    AUTH_TOKEN_MISSING: 'AUTH_003',
    AUTH_TOKEN_INVALID: 'AUTH_004',
    AUTH_TOKEN_EXPIRED: 'AUTH_005',
    AUTH_TOKEN_BLACKLISTED: 'AUTH_006',
    AUTH_UNAUTHORIZED: 'AUTH_007',
    AUTH_ACCESS_FORBIDDEN: 'AUTH_008',

    // User Registration Errors
    USER_ALREADY_EXISTS: 'USER_001',
    USER_EMAIL_EXISTS: 'USER_002',
    USER_USERNAME_EXISTS: 'USER_003',
    USER_MOBILE_EXISTS: 'USER_004',
    USER_CREATION_FAILED: 'USER_005',
    USER_BALANCE_NOT_SETTLED: 'USER_006',

    // Validation Errors
    VALIDATION_REQUIRED_FIELD: 'VAL_001',
    VALIDATION_INVALID_FORMAT: 'VAL_002',
    VALIDATION_FIELD_TOO_SHORT: 'VAL_003',
    VALIDATION_FIELD_TOO_LONG: 'VAL_004',
    VALIDATION_INVALID_EMAIL: 'VAL_005',
    VALIDATION_WEAK_PASSWORD: 'VAL_006',

    // Server Errors
    DATABASE_CONNECTION_ERROR: 'DB_001',
    DATABASE_OPERATION_ERROR: 'DB_002',
    SERVER_INTERNAL_ERROR: 'SRV_001',
    SERVICE_UNAVAILABLE: 'SRV_002',

    // Group Messages
    GROUP_NOT_FOUND: 'GRP_001',
    GROUP_BALANCE_NOT_SETTLED: 'GRP_002',
    GROUP_CREATION_FAILED: 'GRP_003',
    GROUP_MEMBER_ADD_FAILED: 'GRP_004',
    GROUP_MEMBER_REMOVE_FAILED: 'GRP_005',
    GROUP_ACCESS_DENIED: 'GRP_006',
    GROUP_ADMIN_REQUIRED: 'GRP_007',
    GROUP_NAME_REQUIRED: 'GRP_008',
    GROUP_MEMBERS_REQUIRED: 'GRP_009',
    GROUP_INVALID_MEMBER: 'GRP_010',
    GROUP_MEMBER_ALREADY_EXISTS: 'GRP_011',
    GROUP_CANNOT_REMOVE_ADMIN: 'GRP_012',
    GROUP_CANNOT_REMOVE_SELF: 'GRP_013',
    GROUP_DELETE_FAILED: 'GRP_014',
    GROUP_UPDATE_FAILED: 'GRP_015',
    GROUP_SLUG_GENERATION_FAILED: 'GRP_016',

    // Transaction Errors
    TRANSACTION_NOT_FOUND: 'TXN_001',
    TRANSACTION_CREATION_FAILED: 'TXN_002',
    TRANSACTION_UPDATE_FAILED: 'TXN_003',
    TRANSACTION_DELETE_FAILED: 'TXN_004',

    // Token Management Errors
    TOKEN_CREATION_FAILED: 'TKN_001',
    TOKEN_BLACKLIST_FAILED: 'TKN_002',
    TOKEN_CLEANUP_FAILED: 'TKN_003'
};