export const errorCodes = {
    //AUTHENTICATION CODES
    AUTH_INVALID_CREDENTIALS: 'AUTH_001',
    AUTH_USER_NOT_FOUND: 'AUTH_002',
    AUTH_TOKEN_MISSING: 'AUTH_003',
    AUTH_TOKEN_INVALID: 'AUTH_004',
    AUTH_TOKEN_EXPIRED: 'AUTH_005',
    AUTH_TOKEN_BLACKLISTED: 'AUTH_006',
    AUTH_UNAUTHORIZED: 'AUTH_007',
    AUTH_ACCESS_FORBIDDEN: 'AUTH_008',
    
    // User Registration Errors
    USER_ALREADY_EXISTS: 'USER_001',
    USER_EMAIL_EXISTS: 'USER_002',
    USER_USERNAME_EXISTS: 'USER_003',
    USER_MOBILE_EXISTS: 'USER_004',
    USER_CREATION_FAILED: 'USER_005',
    USER_BALANCE_NOT_SETTLED: 'USER_006',
    
    // Validation Errors
    VALIDATION_REQUIRED_FIELD: 'VAL_001',
    VALIDATION_INVALID_FORMAT: 'VAL_002',
    VALIDATION_FIELD_TOO_SHORT: 'VAL_003',
    VALIDATION_FIELD_TOO_LONG: 'VAL_004',
    VALIDATION_INVALID_EMAIL: 'VAL_005',
    VALIDATION_WEAK_PASSWORD: 'VAL_006',
    
    // Server Errors
    DATABASE_CONNECTION_ERROR: 'DB_001',
    DATABASE_OPERATION_ERROR: 'DB_002',
    SERVER_INTERNAL_ERROR: 'SRV_001',
    SERVICE_UNAVAILABLE: 'SRV_002',
    
    // Token Management Errors
    TOKEN_CREATION_FAILED: 'TKN_001',
    TOKEN_BLACKLIST_FAILED: 'TKN_002',
    TOKEN_CLEANUP_FAILED: 'TKN_003'
};